"""Generate font subset CSS for Noto Sans SC.

Collects all Chinese characters from codebase + seed data + known
UI labels, then produces a Google Fonts CSS with text= parameter
for the core character set (static UI). UGC characters fall back
to system fonts.

Usage: python scripts/fonts/build_subset.py
Output: scustack-web/public/fonts/subset.css
"""

import os
import re
from pathlib import Path

ROOT = Path(__file__).parent.parent.parent

# ── Collect characters from codebase ──

CHINESE = re.compile(r'[一-鿿]')

def collect_from_dir(dir_path: str, exts: tuple[str, ...]) -> set[str]:
    chars: set[str] = set()
    for root, _, files in os.walk(dir_path):
        for f in files:
            if f.endswith(exts) and 'node_modules' not in root and '.output' not in root:
                try:
                    content = Path(root, f).read_text(encoding='utf-8')
                    chars.update(CHINESE.findall(content))
                except Exception:
                    pass
    return chars

# Frontend codebase
frontend_chars = collect_from_dir(str(ROOT / 'scustack-web'), ('.vue', '.ts', '.json'))
# Backend seed data (college names, course names, category labels etc)
seed_chars = collect_from_dir(str(ROOT / 'scustack-api' / 'scripts'), ('.py',))
# Backend schemas (badge labels etc)
schema_chars = collect_from_dir(str(ROOT / 'scustack-api' / 'app' / 'schemas'), ('.py',))
# Backend services (label strings)
service_chars = collect_from_dir(str(ROOT / 'scustack-api' / 'app' / 'services'), ('.py',))

core_chars = sorted(frontend_chars | seed_chars | schema_chars | service_chars)
core_text = ''.join(core_chars)

print(f'Characters collected: {len(core_chars)}')

# ── Generate Google Fonts CSS with text= parameter ──

# Google Fonts text= has practical limit ~500 chars per URL.
# For >500 chars, we split into multiple @font-face blocks with
# incremental unicode-range.

# For simplicity, we serve all chars in a single text= param.
# Google supports up to ~2000 chars per request in practice.

WEIGHTS = '300;400;500;600;700'
FONT_FAMILY = 'Noto Sans SC'

css = f"""/* Noto Sans SC subset — {len(core_chars)} characters, generated by scripts/fonts/build_subset.py */

/* Critical subset: UI + known labels (~{len(core_chars)} chars) */
@font-face {{
  font-family: '{FONT_FAMILY}';
  font-style: normal;
  font-weight: 300 700;
  font-display: swap;
  src: url(https://fonts.googleapis.com/css2?family={FONT_FAMILY.replace(' ', '+')}:wght@{WEIGHTS}&text={requests.utils.quote(core_text, safe='')}) format('woff2');
  unicode-range: U+4E00-9FFF;
}}
"""

import requests.utils

output_dir = ROOT / 'scustack-web' / 'public' / 'fonts'
output_dir.mkdir(parents=True, exist_ok=True)
(output_dir / 'subset.css').write_text(css, encoding='utf-8')
print(f'Wrote {output_dir / "subset.css"}')
print(f'Estimated subset size: ~{len(core_chars) * 100 // 1024}KB per weight')
